// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: scheduler.proto

package scheduler

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDailyEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute        int32                  `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDailyEventRequest) Reset() {
	*x = CreateDailyEventRequest{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDailyEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDailyEventRequest) ProtoMessage() {}

func (x *CreateDailyEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDailyEventRequest.ProtoReflect.Descriptor instead.
func (*CreateDailyEventRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDailyEventRequest) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *CreateDailyEventRequest) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

type CreateDailyEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDailyEventResponse) Reset() {
	*x = CreateDailyEventResponse{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDailyEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDailyEventResponse) ProtoMessage() {}

func (x *CreateDailyEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDailyEventResponse.ProtoReflect.Descriptor instead.
func (*CreateDailyEventResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDailyEventResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\tscheduler\"E\n" +
	"\x17CreateDailyEventRequest\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\x05R\x06minute\"1\n" +
	"\x18CreateDailyEventResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2p\n" +
	"\x11SchedulerSService\x12[\n" +
	"\x10CreateDailyEvent\x12\".scheduler.CreateDailyEventRequest\x1a#.scheduler.CreateDailyEventResponseB5Z3github.com/Georgi-Progger/proto/scheduler;schedulerb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scheduler_proto_goTypes = []any{
	(*CreateDailyEventRequest)(nil),  // 0: scheduler.CreateDailyEventRequest
	(*CreateDailyEventResponse)(nil), // 1: scheduler.CreateDailyEventResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.SchedulerSService.CreateDailyEvent:input_type -> scheduler.CreateDailyEventRequest
	1, // 1: scheduler.SchedulerSService.CreateDailyEvent:output_type -> scheduler.CreateDailyEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
