// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: scheduler.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerSService_CreateJob_FullMethodName = "/scheduler.SchedulerSService/CreateJob"
)

// SchedulerSServiceClient is the client API for SchedulerSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerSServiceClient interface {
	CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error)
}

type schedulerSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerSServiceClient(cc grpc.ClientConnInterface) SchedulerSServiceClient {
	return &schedulerSServiceClient{cc}
}

func (c *schedulerSServiceClient) CreateJob(ctx context.Context, in *CreateJobRequest, opts ...grpc.CallOption) (*CreateJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateJobResponse)
	err := c.cc.Invoke(ctx, SchedulerSService_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerSServiceServer is the server API for SchedulerSService service.
// All implementations must embed UnimplementedSchedulerSServiceServer
// for forward compatibility.
type SchedulerSServiceServer interface {
	CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error)
	mustEmbedUnimplementedSchedulerSServiceServer()
}

// UnimplementedSchedulerSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerSServiceServer struct{}

func (UnimplementedSchedulerSServiceServer) CreateJob(context.Context, *CreateJobRequest) (*CreateJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedSchedulerSServiceServer) mustEmbedUnimplementedSchedulerSServiceServer() {}
func (UnimplementedSchedulerSServiceServer) testEmbeddedByValue()                           {}

// UnsafeSchedulerSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerSServiceServer will
// result in compilation errors.
type UnsafeSchedulerSServiceServer interface {
	mustEmbedUnimplementedSchedulerSServiceServer()
}

func RegisterSchedulerSServiceServer(s grpc.ServiceRegistrar, srv SchedulerSServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulerSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerSService_ServiceDesc, srv)
}

func _SchedulerSService_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerSServiceServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerSService_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerSServiceServer).CreateJob(ctx, req.(*CreateJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerSService_ServiceDesc is the grpc.ServiceDesc for SchedulerSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.SchedulerSService",
	HandlerType: (*SchedulerSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJob",
			Handler:    _SchedulerSService_CreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
